server:
  port: 8080
  
spring:
  application:
    name: digistrict-gateway-service
  cloud:
    gateway:
      routes:
      - id: digistrict-api-service
        uri: lb://DIGISTRICT-API-SERVICE
        predicates:
        - Path=/digistrict-api/**
  
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
    - url: /v3/api-docs
      name: API Gateway Service
    - url: /digistrict-api/v3/api-docs
      name: Digistrict Service